apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-practice
  namespace: bqnq
  labels:
    app.kubernetes.io/name: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: fastapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastapi
    spec:
      containers:
      - name: fastapi
        image: ghcr.io/gen0x39/container-practice:latest
        ports:
        - containerPort: 80
        env:
        - name: MODULE_NAME
          value: "main"
        - name: VARIABLE_NAME
          value: "app"
        - name: PORT
          value: "80"
