apiVersion: v1
kind: Service
metadata:
  name: container-practice
  namespace: bqnq
spec:
  selector:
    app.kubernetes.io/name: fastapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
