apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: container-practice
  namespace: argocd
  finalizers:
  - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: https://github.com/gen0x39/container-practice
    targetRevision: main
    path: manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: bqnq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10
