# バックエンドのリソースを増加（CPU負荷テスト用）
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bqnq
  labels:
    app.kubernetes.io/name: backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/gen0x39/container-practice/backend
    argocd-image-updater.argoproj.io/backend.update-strategy: semver
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^(latest|v[0-9]+\.[0-9]+\.[0-9]+|[a-f0-9]{7,})$
    argocd-image-updater.argoproj.io/backend.force-update: "true"
    argocd-image-updater.argoproj.io/backend.pull-secret: pullsecret:argocd/ghcr-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/gen0x39/container-practice/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 500m         # 0.5 CPU core
            memory: 512Mi     # 512MB RAM
          limits:
            cpu: 1000m        # 1 CPU core
            memory: 1Gi       # 1GB RAM
        env:
        - name: MODULE_NAME
          value: "main"
        - name: VARIABLE_NAME
          value: "app"
        - name: PORT
          value: "9000"
        - name: ENVIRONMENT
          value: "production"
        - name: OTEL_SERVICE_NAME
          value: "backend-service"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"  # datadogからotlpに変更
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://datadog-agent.monitoring.svc.cluster.local:4317"  # OTLPエンドポイント
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=backend-service,service.version=1.0.0,deployment.environment=production"
        - name: OTEL_PYTHON_FASTAPI_EXCLUDED_URLS
          value: "health"
          