apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bqnq
  labels:
    app.kubernetes.io/name: backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/gen0x39/container-practice/backend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^(latest|v[0-9]+\.[0-9]+\.[0-9]+)$
    argocd-image-updater.argoproj.io/backend.force-update: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/gen0x39/container-practice/backend:27aa5b4
        ports:
        - containerPort: 9000
        env:
        - name: MODULE_NAME
          value: "main"
        - name: VARIABLE_NAME
          value: "app"
        - name: PORT
          value: "9000"
        - name: ENVIRONMENT
          value: "production"  # 本番環境
          