apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: bqnq
spec:
  selector:
    app.kubernetes.io/name: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
