apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bqnq
  labels:
    app.kubernetes.io/name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/gen0x39/container-practice/frontend:27aa5b4
        ports:
        - containerPort: 4200
