apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bqnq
  labels:
    app.kubernetes.io/name: frontend
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=ghcr.io/gen0x39/container-practice/frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^(latest|v[0-9]+\.[0-9]+\.[0-9]+)$
    argocd-image-updater.argoproj.io/frontend.force-update: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/gen0x39/container-practice/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4200
        resources:
          requests:
            cpu: 500m        # 300m → 500m に増加
            memory: 1Gi      # 512Mi → 1Gi に増加
          limits:
            cpu: 1000m       # 500m → 1000m に増加
            memory: 2Gi      # 1Gi → 2Gi に増加
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4200"
        - name: OTLP_TRACE_EXPORTER_URL
          value: "http://datadog-agent.monitoring.svc.cluster.local:4318/v1/traces"
