apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: bqnq
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4200
  type: ClusterIP
