apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bqnq
  labels:
    app.kubernetes.io/name: frontend
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=ghcr.io/gen0x39/container-practice/frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: semver
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^(latest|v[0-9]+\.[0-9]+\.[0-9]+|[a-f0-9]{7,})$ # SHAタグも許可
    argocd-image-updater.argoproj.io/frontend.force-update: "true"
    argocd-image-updater.argoproj.io/frontend.pull-secret: pullsecret:argocd/ghcr-secret
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/gen0x39/container-practice/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4200
